### ISSUE TITLE
支持增量更新数据吗？

### ISSUE THREAD

**Issue by AGDholo** [xiaohuoni/umi-hzb#2]

**Comment by xiaohuoni** [comment]
想要一个什么效果？
我能想到的是如果开启增量模式，则判断是否有新文件产生。这个只能匹配新文件。

或者依赖 git ，依赖 git 则需要记录 commit id，每次执行的时候要求当前 git 是干净的，感觉这个很不好用。

**Comment by AGDholo** [comment]
> 想要一个什么效果？ 我能想到的是如果开启增量模式，则判断是否有新文件产生。这个只能匹配新文件。

增量模式可能好一点，类似的产品也有这个问题： 
https://github.com/datafuselabs/askbend/issues/43

https://github.com/supabase-community/nextjs-openai-doc-search#-build-time 已经支持了增量更新

**Comment by xiaohuoni** [comment]
要做这么完整嘛！惊

**Comment by xiaohuoni** [comment]
我傻了，我都读到文件了！
